/** Desktop emoji picker catalog — searchable by EN/PT keywords. */
export const EMOJI_CATALOG = [
  { emoji: "🍔", keywords: "burger hamburger food comida lanche" },
  { emoji: "🍕", keywords: "pizza food comida" },
  { emoji: "☕", keywords: "coffee cafe cafezinho drink bebida" },
  { emoji: "🍺", keywords: "beer cerveja drink bebida bar" },
  { emoji: "🍻", keywords: "cheers beer cerveja drinks" },
  { emoji: "🍷", keywords: "wine vinho drink bebida" },
  { emoji: "🥤", keywords: "soda refrigerante drink bebida" },
  { emoji: "🧃", keywords: "juice suco drink bebida" },
  { emoji: "🍎", keywords: "apple maca fruit fruta food" },
  { emoji: "🥗", keywords: "salad salada healthy saudavel food" },
  { emoji: "🍣", keywords: "sushi japanese japones food comida" },
  { emoji: "🍜", keywords: "ramen noodles food comida" },
  { emoji: "🍦", keywords: "ice cream sorvete dessert doce" },
  { emoji: "🍰", keywords: "cake bolo dessert doce" },
  { emoji: "🥐", keywords: "croissant bakery padaria breakfast cafe" },
  { emoji: "🥡", keywords: "takeout delivery comida" },
  { emoji: "🍽️", keywords: "restaurant restaurante dinner jantar food" },
  { emoji: "🚗", keywords: "car carro auto vehicle transporte" },
  { emoji: "🚕", keywords: "taxi uber transporte" },
  { emoji: "🚌", keywords: "bus onibus transporte" },
  { emoji: "🚆", keywords: "train trem metro transporte" },
  { emoji: "✈️", keywords: "plane airplane aviao travel viagem" },
  { emoji: "🚢", keywords: "ship boat barco cruise cruise viagem" },
  { emoji: "⛽", keywords: "gas fuel combustivel gasolina posto" },
  { emoji: "🅿️", keywords: "parking estacionamento" },
  { emoji: "🚲", keywords: "bike bicycle bicicleta" },
  { emoji: "🛵", keywords: "scooter moto motorcycle" },
  { emoji: "🏠", keywords: "home house casa moradia" },
  { emoji: "🏡", keywords: "house home casa jardim" },
  { emoji: "🏢", keywords: "office building predio empresa work" },
  { emoji: "🏨", keywords: "hotel travel viagem" },
  { emoji: "🏥", keywords: "hospital health saude medical" },
  { emoji: "🏦", keywords: "bank banco finance financas" },
  { emoji: "🏪", keywords: "store shop loja mercado" },
  { emoji: "🛒", keywords: "cart grocery compras mercado shopping" },
  { emoji: "🛍️", keywords: "bags shopping compras" },
  { emoji: "🎁", keywords: "gift presente birthday aniversario" },
  { emoji: "📦", keywords: "box package caixa delivery encomenda" },
  { emoji: "💊", keywords: "pill medicine remedio pharmacy farmacia" },
  { emoji: "🩺", keywords: "stethoscope doctor medico health saude" },
  { emoji: "🦷", keywords: "tooth dentist dentista" },
  { emoji: "💉", keywords: "syringe vaccine vacina health" },
  { emoji: "👓", keywords: "glasses oculos vision" },
  { emoji: "🎮", keywords: "game games jogo gaming" },
  { emoji: "🎬", keywords: "movie cinema film filme entertainment" },
  { emoji: "🎵", keywords: "music musica song spotify" },
  { emoji: "🎧", keywords: "headphones fone music musica" },
  { emoji: "🎤", keywords: "mic karaoke music" },
  { emoji: "📺", keywords: "tv television netflix streaming" },
  { emoji: "🎟️", keywords: "ticket ingresso event evento" },
  { emoji: "🎭", keywords: "theater teatro arts cultura" },
  { emoji: "🎨", keywords: "art arte paint pintura hobby" },
  { emoji: "📱", keywords: "phone celular smartphone mobile" },
  { emoji: "💻", keywords: "laptop computer computador tech" },
  { emoji: "🖥️", keywords: "desktop computer monitor tech" },
  { emoji: "⌨️", keywords: "keyboard teclado tech" },
  { emoji: "🖨️", keywords: "printer impressora office" },
  { emoji: "🔌", keywords: "plug eletricidade utilities" },
  { emoji: "💡", keywords: "bulb luz idea ideia light" },
  { emoji: "📡", keywords: "satellite internet wifi signal" },
  { emoji: "📚", keywords: "books livros study estudo education" },
  { emoji: "📖", keywords: "book livro reading leitura" },
  { emoji: "🎓", keywords: "graduation formatura education escola universidade" },
  { emoji: "✏️", keywords: "pencil lapis write escrever" },
  { emoji: "📝", keywords: "memo note nota write" },
  { emoji: "💼", keywords: "briefcase mala work trabalho business" },
  { emoji: "👔", keywords: "tie necktie work trabalho formal" },
  { emoji: "💰", keywords: "money dinheiro bag saco cash" },
  { emoji: "💵", keywords: "dollar cash dinheiro bill" },
  { emoji: "💸", keywords: "flying money gasto spend cash" },
  { emoji: "💳", keywords: "card credito cartao credit debit" },
  { emoji: "📈", keywords: "chart up investimento invest growth lucro" },
  { emoji: "📉", keywords: "chart down loss prejuizo" },
  { emoji: "📊", keywords: "bar chart graficos stats analytics" },
  { emoji: "🧾", keywords: "receipt recibo invoice fatura bill" },
  { emoji: "🪙", keywords: "coin moeda crypto bitcoin" },
  { emoji: "💎", keywords: "gem diamond joia luxury" },
  { emoji: "💲", keywords: "dollar sign dinheiro money" },
  { emoji: "🏧", keywords: "atm banco bank cash" },
  { emoji: "👕", keywords: "shirt camisa clothes roupa" },
  { emoji: "👗", keywords: "dress vestido clothes moda" },
  { emoji: "👟", keywords: "shoe tenis sneakers shoes" },
  { emoji: "👠", keywords: "heels sapato shoes" },
  { emoji: "👜", keywords: "handbag bolsa bag" },
  { emoji: "🧢", keywords: "cap bone hat" },
  { emoji: "🧥", keywords: "coat casaco jacket" },
  { emoji: "💍", keywords: "ring anel jewelry joia" },
  { emoji: "❤️", keywords: "heart coracao love amor health" },
  { emoji: "💔", keywords: "broken heart coracao partido" },
  { emoji: "⭐", keywords: "star estrela favorite favorito" },
  { emoji: "✨", keywords: "sparkles brilho magic" },
  { emoji: "🔥", keywords: "fire fogo hot" },
  { emoji: "⚡", keywords: "zap lightning raio energy energia" },
  { emoji: "💧", keywords: "droplet water agua utilities" },
  { emoji: "☀️", keywords: "sun sol weather clima" },
  { emoji: "🌙", keywords: "moon lua night noite" },
  { emoji: "❄️", keywords: "snow neve cold frio" },
  { emoji: "🔧", keywords: "wrench chave repair reparo tools" },
  { emoji: "🛠️", keywords: "tools ferramentas repair manutencao" },
  { emoji: "🔨", keywords: "hammer martelo tools" },
  { emoji: "🧱", keywords: "brick tijolo construction obra" },
  { emoji: "🧹", keywords: "broom vassoura cleaning limpeza" },
  { emoji: "🧼", keywords: "soap sabao cleaning limpeza" },
  { emoji: "🧺", keywords: "basket cesta laundry lavanderia" },
  { emoji: "🐾", keywords: "paw pet animal pets" },
  { emoji: "🐶", keywords: "dog cao cachorro pet" },
  { emoji: "🐱", keywords: "cat gato pet" },
  { emoji: "🐟", keywords: "fish peixe pet aquarium" },
  { emoji: "🌱", keywords: "seedling planta plant garden jardim" },
  { emoji: "🪴", keywords: "potted plant planta vaso" },
  { emoji: "🌳", keywords: "tree arvore nature natureza" },
  { emoji: "🌸", keywords: "flower flor nature" },
  { emoji: "🏋️", keywords: "gym academia fitness workout" },
  { emoji: "🏃", keywords: "run correr fitness sport" },
  { emoji: "⚽", keywords: "soccer futebol sport esporte" },
  { emoji: "🏀", keywords: "basketball basquete sport" },
  { emoji: "🎾", keywords: "tennis tenis sport" },
  { emoji: "🧘", keywords: "yoga meditation meditacao wellness" },
  { emoji: "🎯", keywords: "target alvo goal meta" },
  { emoji: "🚀", keywords: "rocket foguete startup launch" },
  { emoji: "▶️", keywords: "play streaming video subscription" },
  { emoji: "↩️", keywords: "return refund estorno back" },
  { emoji: "📅", keywords: "calendar calendario schedule agenda" },
  { emoji: "⏰", keywords: "alarm clock relogio time hora" },
  { emoji: "🔔", keywords: "bell sino notification alerta" },
  { emoji: "📍", keywords: "pin location localizacao mapa" },
  { emoji: "🗺️", keywords: "map mapa travel viagem" },
  { emoji: "🏖️", keywords: "beach praia vacation ferias" },
  { emoji: "🌴", keywords: "palm palmeira tropical vacation" },
  { emoji: "⛺", keywords: "tent camping trip" },
  { emoji: "🎿", keywords: "ski neve winter" },
  { emoji: "👶", keywords: "baby bebe kids crianca" },
  { emoji: "🧸", keywords: "teddy ursinho kids brinquedo" },
  { emoji: "👨‍👩‍👧", keywords: "family familia kids" },
  { emoji: "💒", keywords: "wedding casamento church igreja" },
  { emoji: "⛪", keywords: "church igreja religion religiao" },
  { emoji: "🙏", keywords: "pray oracao thanks obrigado" },
  { emoji: "🎉", keywords: "party festa celebration celebracao" },
  { emoji: "🥳", keywords: "party face festa birthday" },
  { emoji: "🎂", keywords: "birthday cake bolo aniversario" },
  { emoji: "🎄", keywords: "christmas natal holiday" },
  { emoji: "🎃", keywords: "halloween abobora" },
  { emoji: "🐈", keywords: "cat gato pet" },
  { emoji: "🦄", keywords: "unicorn unicorno fun" },
  { emoji: "🧀", keywords: "cheese queijo food" },
  { emoji: "🥑", keywords: "avocado abacate healthy" },
  { emoji: "🍌", keywords: "banana fruit fruta" },
  { emoji: "🍇", keywords: "grapes uva fruit" },
  { emoji: "🍩", keywords: "donut doce dessert" },
  { emoji: "🍪", keywords: "cookie biscoito" },
  { emoji: "🍫", keywords: "chocolate doce" },
  { emoji: "🧩", keywords: "puzzle hobby" },
  { emoji: "♟️", keywords: "chess xadrez hobby" },
  { emoji: "🎲", keywords: "dice dado games jogo" },
  { emoji: "🕹️", keywords: "joystick arcade gaming" },
  { emoji: "📷", keywords: "camera foto photography" },
  { emoji: "📹", keywords: "video camera filmagem" },
  { emoji: "🔑", keywords: "key chave password senha" },
  { emoji: "🛡️", keywords: "shield protecao insurance seguro" },
  { emoji: "⚖️", keywords: "scales justica legal advogado" },
  { emoji: "📜", keywords: "scroll documento contrato" },
  { emoji: "🗂️", keywords: "folders arquivos files docs" },
  { emoji: "📞", keywords: "phone telefone call ligacao" },
  { emoji: "💬", keywords: "chat mensagem message sms" },
  { emoji: "📧", keywords: "email email correio" },
  { emoji: "🌐", keywords: "globe internet web world mundo" },
  { emoji: "☁️", keywords: "cloud nuvem saas subscription" },
  { emoji: "🗑️", keywords: "trash lixeira delete" },
  { emoji: "✅", keywords: "check ok done concluido" },
  { emoji: "❌", keywords: "cross x cancel erro" },
  { emoji: "⚠️", keywords: "warning alerta cuidado" },
  { emoji: "💯", keywords: "hundred cem percent" },
  { emoji: "🆕", keywords: "new novo" },
  { emoji: "🆓", keywords: "free gratis" },
  { emoji: "🔝", keywords: "top cima" },
  { emoji: "➕", keywords: "plus mais add" },
  { emoji: "➖", keywords: "minus menos" },
  { emoji: "➗", keywords: "divide dividir math" },
  { emoji: "✖️", keywords: "multiply vezes math" },
  { emoji: "♿", keywords: "wheelchair acessibilidade" },
  { emoji: "🚭", keywords: "no smoking" },
  { emoji: "♻️", keywords: "recycle reciclagem eco" },
  { emoji: "🟢", keywords: "green circle verde" },
  { emoji: "🔴", keywords: "red circle vermelho" },
  { emoji: "🔵", keywords: "blue circle azul" },
  { emoji: "🟡", keywords: "yellow circle amarelo" },
  { emoji: "🟣", keywords: "purple circle roxo" },
  { emoji: "⚫", keywords: "black circle preto" },
  { emoji: "⚪", keywords: "white circle branco" },
  { emoji: "🧡", keywords: "orange heart coracao laranja" },
  { emoji: "💛", keywords: "yellow heart coracao amarelo" },
  { emoji: "💚", keywords: "green heart coracao verde" },
  { emoji: "💙", keywords: "blue heart coracao azul" },
  { emoji: "💜", keywords: "purple heart coracao roxo" },
  { emoji: "🖤", keywords: "black heart coracao preto" },
  { emoji: "🤍", keywords: "white heart coracao branco" },
  { emoji: "🤎", keywords: "brown heart coracao marrom" },
];

const EMOJI_CHAR_RE =
  /(?:\p{Extended_Pictographic}(?:\uFE0F|\u200D\p{Extended_Pictographic}|\u200D\p{Emoji_Modifier_Base}|\p{Emoji_Modifier})*)/u;

export function extractEmoji(value) {
  if (!value || typeof value !== "string") {
    return "";
  }
  const trimmed = value.trim();
  if (!trimmed) {
    return "";
  }
  if (typeof Intl !== "undefined" && Intl.Segmenter) {
    const segmenter = new Intl.Segmenter(undefined, { granularity: "grapheme" });
    for (const { segment } of segmenter.segment(trimmed)) {
      if (EMOJI_CHAR_RE.test(segment) || /[\u2600-\u27BF]/.test(segment)) {
        return segment;
      }
    }
  }
  const match = trimmed.match(EMOJI_CHAR_RE);
  return match ? match[0] : "";
}

export function filterEmojiCatalog(query) {
  const q = query.trim().toLowerCase();
  if (!q) {
    return EMOJI_CATALOG;
  }
  const asEmoji = extractEmoji(q);
  if (asEmoji && q.replace(/\s/g, "").length <= asEmoji.length + 2) {
    const exact = EMOJI_CATALOG.filter((item) => item.emoji === asEmoji);
    if (exact.length) {
      return exact;
    }
    return [{ emoji: asEmoji, keywords: "custom" }];
  }
  return EMOJI_CATALOG.filter(
    (item) =>
      item.keywords.includes(q) ||
      item.emoji.includes(q) ||
      item.keywords.split(/\s+/).some((word) => word.startsWith(q))
  );
}
